from django.urls import path

from bar.views import (
    index,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    GenreListView,
    GenreDetailView,
    GenreUpdateView,
    GenreCreateView,
    GenreDeleteView,
    MusicianListView,
    MusicianDetailView,
    MusicianCreateView,
    MusicianUpdateView,
    MusicianDeleteView,
    RockbandListView,
    RockbandDetailView,
    RockbandCreateView,
    RockbandUpdateView,
    RockbandDeleteView,
    EventListView,
    EventDetailView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
    VisitorDetailView,
    VisitorCreateView,
    VisitorDeleteView, toggle_assign_to_events, VisitorListView)

urlpatterns = [
    path("", index, name="index"),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path(
        "genres/",
        GenreListView.as_view(),
        name="genre-list",
    ),
    path(
        "genres/<int:pk>/",
        GenreDetailView.as_view(),
        name="genre-detail",
    ),
    path(
        "genres/create/",
        GenreCreateView.as_view(),
        name="genre-create",
    ),
    path(
        "genres/<int:pk>/update/",
        GenreUpdateView.as_view(),
        name="genre-update",
    ),
    path(
        "genres/<int:pk>/delete/",
        GenreDeleteView.as_view(),
        name="genre-delete",
    ),
    path(
        "musicians/",
        MusicianListView.as_view(),
        name="musician-list",
    ),
    path(
        "musicians/<int:pk>/",
        MusicianDetailView.as_view(),
        name="musician-detail",
    ),
    path(
        "musicians/create/",
        MusicianCreateView.as_view(),
        name="musician-create",
    ),
    path(
        "musicians/<int:pk>/update/",
        MusicianUpdateView.as_view(),
        name="musician-update",
    ),
    path(
        "musicians/<int:pk>/delete/",
        MusicianDeleteView.as_view(),
        name="musician-delete",
    ),
    path(
        "rockbands/",
        RockbandListView.as_view(),
        name="rockband-list",
    ),
    path(
        "rockbands/<int:pk>/",
        RockbandDetailView.as_view(),
        name="rockband-detail",
    ),
    path(
        "rockbands/create/",
        RockbandCreateView.as_view(),
        name="rockband-create",
    ),
    path(
        "rockbands/<int:pk>/update/",
        RockbandUpdateView.as_view(),
        name="rockband-update",
    ),
    path(
        "rockbands/<int:pk>/delete/",
        RockbandDeleteView.as_view(),
        name="rockband-delete",
    ),
    path(
        "events/",
        EventListView.as_view(),
        name="event-list",
    ),
    path(
        "events/<int:pk>/",
        EventDetailView.as_view(),
        name="event-detail",
    ),
    path(
        "events/create/",
        EventCreateView.as_view(),
        name="event-create",
    ),
    path(
        "events/<int:pk>/update/",
        EventUpdateView.as_view(),
        name="event-update",
    ),
    path(
        "events/<int:pk>/delete/",
        EventDeleteView.as_view(),
        name="event-delete",
    ),
    path(
        "events/<int:pk>/toggle-assign/",
        toggle_assign_to_events,
        name="toggle-events-assign",
    ),
    path(
        "visitors/",
        VisitorListView.as_view(),
        name="visitor-list",
    ),
    path(
        "visitors/<int:pk>/",
        VisitorDetailView.as_view(),
        name="visitor-detail",
    ),
    path(
        "visitors/create/",
        VisitorCreateView.as_view(),
        name="visitor-create",
    ),
    path(
        "visitors/<int:pk>/delete/",
        VisitorDeleteView.as_view(),
        name="visitor-delete",
    ),
]

app_name = "bar"
