# Generated by Django 4.1.7 on 2023-03-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='rockband',
            name='number_of_members',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='ticket_number',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='position',
        ),
        migrations.AddField(
            model_name='musician',
            name='position',
            field=models.ManyToManyField(related_name='musicians', to='bar.position'),
        ),
        migrations.AlterField(
            model_name='rockband',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='bar.genre'),
        ),
    ]
