# Generated by Django 4.1.7 on 2023-03-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_alter_rockband_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rockband',
            name='musicians',
            field=models.ManyToManyField(
                related_name='rockbands',
                to='bar.musician'
            ),
        ),
    ]
